//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB1_Register_Enums.h>

extern unsigned short cnt_zerocross;
extern unsigned short cnt_SW;
extern unsigned short zerocross_timeout;
extern unsigned short input_timeout;
extern unsigned short button_toggle_time;
//-----------------------------------------------------------------------------
// TIMER3_ISR
//-----------------------------------------------------------------------------
//
// TIMER3 ISR Content goes here. Remember to clear flag bits:
// TMR3CN0::TF3H (Timer # High Byte Overflow Flag)
// TMR3CN0::TF3L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER3_ISR, TIMER3_IRQn)
  {
  if(cnt_zerocross > 0) cnt_zerocross--;
  if(cnt_SW > 0) cnt_SW--;
  if(zerocross_timeout > 0)zerocross_timeout--;
  if(input_timeout > 0)input_timeout--;
  if(button_toggle_time > 0) button_toggle_time--;

  TMR3CN0 &= ~(TMR3CN0_TF3L__BMASK);
  TMR3CN0 &= ~(TMR3CN0_TF3H__BMASK);

  }

